services:
  web:
    image: ${DOCKER_IMAGE}:${IMAGE_TAG:-latest}
    container_name: teamchatsa-web
    networks:
      - teamchatsa-net
    restart: unless-stopped
    
networks:
  teamchatsa-net:
    external: true
    name: teamchatsa-net